use_frameworks!

platform :ios, '9.0'

target 'rms-mobile-xdk-cocoapods_Example' do
  pod 'rms-mobile-xdk-cocoapods', :path => '../'

  target 'rms-mobile-xdk-cocoapods_Tests' do
    inherit! :search_paths

    
  end
end
